version: '3.1'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80

  mysql_db_container:
      image: mysql:5.6
      command: --default-authentication-plugin=mysql_native_password
      environment:
        MYSQL_ROOT_PASSWORD: karan
      ports: 
        - 3306:3306
      volumes: 
         - mysql_db_data_container:/var/lib/mysql

  adminer_container:
      image: adminer:latest
      environment: 
          ADMINER_DEFAULT_SERVER: mysql_db_container
          ADMINER_DESIGN: galkaev
      ports: 
        - 8080:8080         

volumes: 
    mysql_db_data_container:      